export const dataProductCart = [
  {
    id: "SP123",
    nameProduct: "Gà không lối thoát",
    note: "Gà không lối thoát được làm từ xôi và gà hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh Gà không lối thoát được làm từ xôi và gà hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh Gà không lối thoát được làm từ xôi và gà hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
    imgProduct: "",
    altImage: "",
    priceProduct: 250000,
    sale: 10,
    quantity: 1,
  },
  {
    id: "SP124",
    nameProduct: "Gà không lối thoát",
    note: "Gà không lối thoát được làm từ xôi và gà hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh Gà không lối thoát được làm từ xôi và gà hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh Gà không lối thoát được làm từ xôi và gà hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
    imgProduct: "",
    altImage: "",
    priceProduct: 250000,
    sale: 10,
    quantity: 1,
  },
  {
    id: "SP125",
    nameProduct: "Gà không lối thoát",
    note: "Gà không lối thoát được làm từ xôi và gà hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh Gà không lối thoát được làm từ xôi và gà hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh Gà không lối thoát được làm từ xôi và gà hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
    imgProduct: "",
    altImage: "",
    priceProduct: 250000,
    sale: 10,
    quantity: 1,
  },
];
